stages:
  - linting
  - formatting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose
    - flake8 . --count --show-source --statistics

black_check:
  stage: formatting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black -l 79 .
    - black -l 79 --check .

django-tests:
  stage: test
  script:
    - pip install -r requirements/prod.txt
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test