# Generated by Django 4.2 on 2023-11-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите Ваш отзыв", verbose_name="Отзыв"
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Напишите Вашу электронную почту",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо обратной связи",
                "verbose_name_plural": "письма обратной связи",
            },
        ),
    ]
