# Generated by Django 4.2 on 2023-11-10 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваше имя",
                max_length=100,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPD", "в обработке"),
                    ("GET", "получено"),
                    ("OK", "ответ дан"),
                ],
                default="GET",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("UPD", "в обработке"),
                            ("GET", "получено"),
                            ("OK", "ответ дан"),
                        ],
                        db_column="from",
                        max_length=15,
                        verbose_name="from",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("UPD", "в обработке"),
                            ("GET", "получено"),
                            ("OK", "ответ дан"),
                        ],
                        db_column="to",
                        max_length=15,
                        verbose_name="to",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
