# Generated by Django 4.2 on 2023-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
