# Generated by Django 4.2 on 2023-10-17 10:37
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        verbose_name="название",
                        unique=True,
                        max_length=150,
                        help_text="Напишите имя",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        "Слаг",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        help_text="Напишите слаг категории",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        "Вес",
                        default=100,
                        validators=[
                            django.core.validators.MaxValueValidator(32767),
                            django.core.validators.MinValueValidator(1),
                        ],
                        help_text="Напишите вес категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        verbose_name="название",
                        unique=True,
                        max_length=150,
                        help_text="Напишите имя",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        "Слаг",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        help_text="Напишите слаг тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        verbose_name="название",
                        unique=True,
                        max_length=150,
                        help_text="Напишите имя",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        "Текст",
                        help_text="Опишите товар",
                        validators=[
                            django.core.validators.RegexValidator(
                                r"(?<![a-zA-Zа-яА-Я0-9])(превосходно|роскошно|"
                                r"Превосходно|Роскошно)(?![a-zA-Zа-яА-Я0-9])",
                                "В тексте должно быть слово превосходно или роскошно",
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
