# Generated by Django 4.2 on 2023-10-18 10:03

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Опишите товар",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно",
                        "роскошно",
                    )
                ],
                verbose_name="Текст",
            ),
        ),
    ]
