# Generated by Django 4.2 on 2023-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalize_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="tag",
            name="normalize_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
