# Generated by Django 4.2 on 2023-10-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0004_mainimage_alter_category_slug_alter_tag_slug_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=True, verbose_name="Опубликованный на главной странице"
            ),
        ),
    ]
