# Generated by Django 4.2 on 2023-10-24 19:51

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0004_mainimage_alter_category_slug_alter_tag_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Опишите товар",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="Текст",
            ),
        ),
    ]
