# Generated by Django 4.2 on 2023-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_item_is_on_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "Главное изображение",
                "verbose_name_plural": "Главные изображения",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
    ]
