# Generated by Django 4.2 on 2023-11-14 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_item_text"),
        ("catalog", "0009_item_created_time_item_updated_time_and_more"),
    ]

    operations = []
